# Default profile
spring.profiles.active=dev

# Swagger
spring.mvc.pathmatch.matching-strategy=ant_path_matcher
springdoc.swagger-ui.path=/docs

# JPA
spring.jpa.open-in-view=true

# JWT
jwt.secret=${JWT_SECRET:defaultSecretKeyForDevelopmentOnlyChangeInProduction}
jwt.expiration=86400000
