#set-up fake database
spring.h2.console.enabled=true
spring.datasource.url = jdbc:h2:mem://localhost:3306/fc_repo
# Change l'URL de Swagger UI
springdoc.swagger-ui.path=/docs
# Choix par défaut pour éviter warning
spring.jpa.open-in-view=true
